"""Transform PMS Generator ``pms_cache.response_json`` → ``PmsGeneratorInput``.

The PMS Generator stores its output in the ``pms_cache`` Postgres table on
Render.  The ``response_json`` column uses a flat format (``rating``,
``material``, ``valves.ball_by_size``, …).  The v2 pipeline expects the
structured ``PmsGeneratorInput`` schema (``code_factors``, ``design_conditions``,
``derived_conditions``, …).

This module bridges the two formats so a **single sync button** can feed both
the v1 pipeline (via ``render_sync.transform``) and the v2 pipeline (via
this transformer → ``POST /api/v2/pms-context``).

If the ``response_json`` already **IS** in ``PmsGeneratorInput`` format (i.e.
generated by a newer PMS Generator build), ``try_parse_native`` succeeds and
no transformation is needed.
"""
from __future__ import annotations

import re
from typing import Any, Optional

from .context_schema import PmsGeneratorInput


# ── Helpers ──────────────────────────────────────────────────────────────────

def _parse_float(v: Any) -> Optional[float]:
    if v is None or v == "":
        return None
    try:
        return float(str(v).split()[0].replace(",", ""))
    except (ValueError, TypeError):
        return None


def _parse_pressure_num(rating: str) -> int:
    m = re.search(r"\d+", str(rating or "150"))
    return int(m.group()) if m else 150


_PRESSURE_LETTER: dict[int, str] = {
    150: "A", 300: "B", 600: "D", 900: "E", 1500: "F", 2500: "G",
}


def _parse_class_parts(spec_code: str) -> tuple[str, str, str]:
    """Split e.g. 'A1N' → ('A', '1', 'N') or 'A10' → ('A', '10', '')."""
    s = spec_code.strip()
    m = re.match(r"^([A-Z])(\d+)(.*?)$", s, re.IGNORECASE)
    if m:
        return m.group(1).upper(), m.group(2), m.group(3).upper()
    return s[0].upper() if s else "A", "1", ""


def _face_code(face_str: str | None) -> str:
    ff = (face_str or "RF").upper()
    if "RTJ" in ff or "RJ" in ff:
        return "RTJ"
    if "FF" in ff or "FLAT" in ff:
        return "FF"
    return "RF"


_MATERIAL_FAMILY_MAP: dict[str, str] = {
    "cs":                   "Carbon Steel",
    "c.s.":                 "Carbon Steel",
    "carbon steel":         "Carbon Steel",
    "cs nace":              "CS NACE",
    "carbon steel nace":    "CS NACE",
    "ltcs":                 "LTCS",
    "low temperature":      "LTCS",
    "316l":                 "SS316L",
    "316":                  "SS316L",
    "stainless":            "SS316L",
    "ss 316l":              "SS316L",
    "ss316l":               "SS316L",
    "ss316l nace":          "SS316L NACE",
    "duplex":               "Duplex",
    "dss":                  "Duplex",
    "super duplex":         "Super Duplex",
    "sdss":                 "Super Duplex",
    "cu-ni":                "CuNi",
    "copper nickel":        "CuNi",
    "bronze":               "Copper",
    "copper":               "Copper",
    "gre":                  "GRE",
    "galv":                 "Galvanised",
    "galvanized":           "Galvanised",
    "cpvc":                 "CPVC",
    "titanium":             "Titanium",
}


def _resolve_family(material_desc: str) -> str:
    """Map PMS material description to a fitting_specs.family label."""
    md = (material_desc or "").strip().lower()
    # Exact match first
    if md in _MATERIAL_FAMILY_MAP:
        return _MATERIAL_FAMILY_MAP[md]
    # Substring match
    for key, val in _MATERIAL_FAMILY_MAP.items():
        if key in md:
            return val
    return material_desc or "Carbon Steel"


def _nace_from_spec(spec_code: str) -> bool:
    return "N" in spec_code.upper()[2:] if len(spec_code) > 2 else False


def _lt_from_spec(spec_code: str) -> bool:
    return "L" in spec_code.upper()[2:] if len(spec_code) > 2 else False


def _build_suffix(spec_code: str) -> str:
    parts = []
    if _lt_from_spec(spec_code):
        parts.append("L")
    if _nace_from_spec(spec_code):
        parts.append("N")
    return "".join(parts)


def _split_vds_codes(cell: str) -> list[str]:
    if not cell:
        return []
    return [c.strip().upper() for c in cell.split(",") if c.strip()]


def _build_valves_section(valves: dict, spec_code: str) -> dict:
    """Build the ValvesSection from ``response_json.valves``."""
    section: dict[str, Any] = {}
    section["rating"] = valves.get("rating") or ""
    section["body"] = valves.get("body_material") or ""

    _TYPE_MAP = {
        "ball_by_size":      "ball",
        "gate_by_size":      "gate",
        "globe_by_size":     "globe",
        "check_by_size":     "check",
        "butterfly_by_size": "butterfly",
        "needle_by_size":    "needle",
        "dbb_by_size":       "dbb",
    }

    for by_size_key, valve_key in _TYPE_MAP.items():
        rows = valves.get(by_size_key)
        if not isinstance(rows, list) or not rows:
            continue
        # Collect all codes across size rows
        all_codes: list[str] = []
        for row in rows:
            if isinstance(row, dict):
                all_codes.extend(_split_vds_codes(row.get("code") or ""))
        if all_codes:
            unique_codes = list(dict.fromkeys(all_codes))
            section[valve_key] = {
                "code": ", ".join(unique_codes),
                "desc": f"{valve_key.title()} valve for {spec_code}",
            }

    return section


# ── Body material resolver (mirrors render_sync._MATERIAL_BODY_MAP) ─────────

_BODY_MAT_MAP = {
    "titanium":       "Titanium Gr 2 per ASME B16.34 Group 4.2",
    "super duplex":   "Forged - ASTM A182 F53 / Cast - ASTM A995 5A",
    "sdss":           "Forged - ASTM A182 F53 / Cast - ASTM A995 5A",
    "duplex":         "Forged - ASTM A182 F60 / Cast - A995 4A",
    "dss":            "Forged - ASTM A182 F60 / Cast - A995 4A",
    "316":            "ASTM A182 F316L / A351 CF3M",
    "stainless":      "ASTM A182 F316L / A351 CF3M",
    "cu-ni":          "ASTM B148 C95800",
    "copper nickel":  "ASTM B148 C95800",
    "carbon":         "ASTM A105N / ASTM A216 WCB",
    "ltcs":           "ASTM A350 LF2 / ASTM A352 LCC",
    "low temp":       "ASTM A350 LF2 / ASTM A352 LCC",
}


def _resolve_valve_body(material_desc: str) -> Optional[str]:
    md = (material_desc or "").lower()
    for key, val in _BODY_MAT_MAP.items():
        if key in md:
            return val
    if md.strip() in ("cs", "c.s.", "carbon steel"):
        return "ASTM A105N / ASTM A216 WCB"
    return None


# ── Main transformer ─────────────────────────────────────────────────────────

def try_parse_native(response_json: dict) -> Optional[PmsGeneratorInput]:
    """If ``response_json`` is already in ``PmsGeneratorInput`` format, parse it.

    Returns ``None`` if the required fields for the new format are missing.
    """
    if not isinstance(response_json, dict):
        return None
    # New format has `code_factors` at the top level — old format doesn't
    if "code_factors" in response_json and "class_code" in response_json:
        try:
            return PmsGeneratorInput(**response_json)
        except Exception:
            return None
    return None


def transform_to_v2(spec_code: str, response_json: dict) -> PmsGeneratorInput:
    """Convert old-format ``response_json`` → ``PmsGeneratorInput``.

    Raises ``ValueError`` if the input is too sparse to build a valid schema.
    """
    rj = response_json or {}
    pc = (spec_code or "").upper().strip()
    letter, digit, _ = _parse_class_parts(pc)
    suffix = _build_suffix(pc)

    material_desc = rj.get("material") or ""
    pressure_num = _parse_pressure_num(rj.get("rating"))

    # ── P-T table ──
    pt = rj.get("pressure_temperature") or {}
    temperatures = [float(t) for t in (pt.get("temperatures") or []) if t is not None]
    pressures = [float(p) for p in (pt.get("pressures") or []) if p is not None]

    design_p = pressures[0] if pressures else float(pressure_num)
    design_t = temperatures[-1] if temperatures else 200.0
    min_temp = temperatures[0] if temperatures else -29.0
    hydrotest = _parse_float(rj.get("hydrotest_pressure"))
    if hydrotest is None:
        hydrotest = round(design_p * 1.5, 1)

    # ── Flange ──
    flange = rj.get("flange") or {}
    flange_mat = flange.get("material_spec") or ""
    face = _face_code(flange.get("face_type"))

    # ── Bolting / gaskets ──
    bng = rj.get("bolts_nuts_gaskets") or {}
    stud = bng.get("stud_bolts") or ""
    nut = bng.get("hex_nuts") or ""
    gasket_spec = bng.get("gasket") or ""
    gasket_type = "Spiral Wound" if "spiral" in gasket_spec.lower() else None

    # ── Valves section ──
    valves_raw = rj.get("valves") or {}
    valves_section = _build_valves_section(valves_raw, pc)

    # ── Build PmsGeneratorInput dict ──
    pms_dict: dict[str, Any] = {
        "class_code": pc,
        "letter": letter,
        "digit": digit,
        "suffix": suffix,
        "service": rj.get("service") or "",
        "note": None,
        "base_class_code": None,
        "code_factors": {
            "fitting_specs": {
                "family": _resolve_family(material_desc),
                "flange": flange_mat or None,
                "valve_body": _resolve_valve_body(material_desc),
            },
            "flange_extras": {
                "face": {"code": face},
                "bolting": {"stud": stud, "hex_nut": nut},
                "gasket": {"type": gasket_type, "spec": gasket_spec},
                "valves": valves_section,
            },
        },
        "design_conditions": {
            "design_pressure_barg": design_p,
            "design_temp_c": design_t,
            "mdmt_c": min_temp,
        },
        "derived_conditions": {
            "pressure": {
                "design_barg": design_p,
                "design_psig": round(design_p * 14.5038, 1),
                "hydrotest_barg": hydrotest,
                "hydrotest_psig": round(hydrotest * 14.5038, 1),
            },
        },
    }

    # ── P-T table (if available) ──
    if temperatures and pressures:
        pms_dict["pressure_temperature"] = {
            "temperatures_c": temperatures,
            "pressures_barg": pressures,
        }

    return PmsGeneratorInput(**pms_dict)
